version: '3.8'

services:
  dsl-backend:
    build: .
    image: dsl-backend
    ports:
      - "8085:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=dsl_db;Database=dsl;Username=postgres;Password=postgres
    container_name: dsl_backend
    depends_on:
      - dsl-db

  dsl-dashboard:
    build: ./dashboard
    ports:
      - "3000:80"
    depends_on:
      - dsl-backend
    container_name: dsl_dashboard

  dsl-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dsl
    ports:
      - "5432:5432"
    container_name: dsl_db
    volumes:
      - dsl_postgres_data:/var/lib/postgresql/data

volumes:
  dsl_postgres_data:

